#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
BEGIN {
    my $lib = "$FindBin::Bin/../../../lib";
    $lib =~ /\A([^\x00-\x1f\x7f]+)\z/ or die "Unsafe Tira library path\n";
    unshift @INC, $1;
}
use Tira::CLI;
exit Tira::CLI->run( command => 'project.create', argv => \@ARGV );

__END__

=head1 NAME

tira.project.create - Create a Tira project

=head1 SYNOPSIS

  dashboard tira.project.create --name NAME [--dir DIR] [-o toon|json|human]

=cut
