#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
BEGIN {
    my $lib = "$FindBin::Bin/../../../../../lib";
    $lib =~ /\A([^\x00-\x1f\x7f]+)\z/ or die "Unsafe Tira library path\n";
    unshift @INC, $1;
}
use Tira::CLI;
exit Tira::CLI->run( command => 'project.people.activate', argv => \@ARGV );

__END__

=head1 NAME

tira.project.people.activate - Reactivate a project person

=head1 SYNOPSIS

  dashboard tira.project.people.activate --id ID [-o toon|json|human]

=cut
