#!/usr/bin/env perl

use strict;
use warnings;
use File::Basename qw(dirname);
use File::Spec;
use FindBin;

my $cursor = $FindBin::Bin;
while ( !-f File::Spec->catfile( $cursor, 'lib', 'Tira', 'CLI.pm' ) ) {
    my $parent = dirname($cursor);
    die "Cannot locate Tira skill root\n" if $parent eq $cursor;
    $cursor = $parent;
}
$cursor =~ /\A([^\x00-\x1f\x7f]+)\z/ or die "Unsafe Tira skill root\n";
my $root = $1;
unshift @INC, File::Spec->catdir( $root, 'lib' );
require Tira::CLI;

exit Tira::CLI->run( command => 'backup', argv => \@ARGV );

__END__

=head1 NAME

tira.backup - Back the board up as a commit in a repository Tira manages

=head1 DESCRIPTION

Locates the Tira repository root and delegates to C<Tira::CLI>, which makes a
commit in a git repository beside the project file. The repository is created
on first use and has no remote.

=cut
