#!/usr/bin/env perl
use strict;
use warnings;
use File::Spec;
use FindBin;
unshift @INC, File::Spec->catdir( $FindBin::Bin, '..', 'lib' );
require Tira::CLI;
exit Tira::CLI->run( command => 'export', argv => \@ARGV );
__END__
=head1 NAME
Tira export - Return every work record in one call
=head1 DESCRIPTION
Exports full SOW, epic, and ticket records with their current columns.
=cut
