#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use File::Spec;

my $manual = File::Spec->catfile( $FindBin::Bin, '..', 'SKILLS.md' );
open my $fh, '<:raw', $manual or die "Cannot read Tira skill manual: $!\n";
print while <$fh>;
close $fh or die "Cannot close Tira skill manual: $!\n";

__END__

=head1 NAME

tira.skills - Print the raw Tira agent manual

=head1 SYNOPSIS

  d2 tira.skills

=cut
