#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename qw(basename dirname);
use File::Spec;
use FindBin;
my $cursor = $FindBin::Bin;
while ( !-f File::Spec->catfile( $cursor, 'lib', 'Tira', 'CLI.pm' ) ) {
    my $parent = dirname($cursor);
    die "Cannot locate Tira skill root\n" if $parent eq $cursor;
    $cursor = $parent;
}
$cursor =~ /\A([^\x00-\x1f\x7f]+)\z/ or die "Unsafe Tira skill root\n";
my $root = $1;
unshift @INC, File::Spec->catdir( $root, 'lib' );
require Tira::CLI;
my $command = 'required-action.' . basename($0);
exit Tira::CLI->run( command => $command, argv => \@ARGV );
__END__
=head1 NAME
Tira required-action command - Manage a card's required-action list
=head1 DESCRIPTION
Delegates required-action operations to the shared Tira command boundary.
=cut
