#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
BEGIN {
    my $lib = "$FindBin::Bin/../../../lib";
    $lib =~ /\A([^\x00-\x1f\x7f]+)\z/ or die "Unsafe Tira library path\n";
    unshift @INC, $1;
}
use Tira::CLI;
exit Tira::CLI->run( command => 'import.jira', argv => \@ARGV );

__END__

=head1 NAME

tira.import.jira - Import a Jira issue's exported XML onto a Tira ticket

=head1 DESCRIPTION

Parses a Jira "Export XML" file (the standard RSS 0.92 issue shape) and
records the Jira issue key and summary as a key-detail on the target Tira
ticket. TKT-1153. C<--author> is required, like every other command that
writes a comment - there is no default person.

    d2 tira.import.jira --ref TKT-123 --file export.xml --author YOU

=cut
