#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename qw(basename dirname);
use File::Spec;
use FindBin;
my $cursor = $FindBin::Bin;
while ( !-f File::Spec->catfile( $cursor, 'lib', 'Tira', 'CLI.pm' ) ) {
    my $parent = dirname($cursor);
    die "Cannot locate Tira skill root\n" if $parent eq $cursor;
    $cursor = $parent;
}
$cursor =~ /\A([^\x00-\x1f\x7f]+)\z/ or die "Unsafe Tira skill root\n";
unshift @INC, File::Spec->catdir( $1, 'lib' );
require Tira::CLI;
exit Tira::CLI->run( command => 'gate.annotate', argv => \@ARGV );
__END__
=head1 NAME
Tira gate annotate - Append a correction to a gate observation
=head1 DESCRIPTION
Adds an attributed note without rewriting the original gate entry.
=cut
