#!/usr/bin/env perl
# TKT-1153. URGENT, owner deadline. Importing a Jira issue's exported XML,
# recording its key as a key-detail on the matching Tira ticket - no sample
# XML was provided, so this targets Jira's own standard, documented
# issue-XML export shape (Export XML action, RSS 0.92-based).
#
# WRITTEN RED.
#
# CODEX REVIEW FIXUP: the first version returned {ok=>0} on refusal, which
# the CLI dispatcher formats as a successful exit(0) - contradicting the
# documented "refuses cleanly" behavior. Every refusal here now dies, like
# every other engine verb, and is asserted through eval/$@. Also added:
# entity/CDATA decoding, multi-issue-export refusal, and the real executable
# (not just the engine sub) for at least the malformed-file and
# real-invocation paths, plus no silent 'claude' author default.

use strict;
use warnings;

use File::Spec;
use File::Temp ();
use Test::More;

use lib 'lib';
use Tira;

require Tira::CLI;
require Tira::CLI::Records;

my $tmp  = File::Temp::tempdir( CLEANUP => 1 );
my $root = File::Spec->catdir( $tmp, 'board' );

my $tira = Tira->new( clock => sub {'2026-09-23T19:00:00Z'} );
$tira->project_new(
    name => 'Jira Import', dir => $root, members => [ 'claude', 'alice' ],
    columns    => ['backlog, done'],
    sow_prefix => 'JIS', epic_prefix => 'JIE', ticket_prefix => 'JIT',
);
my $target = $tira->create_record(
    project => $root, type => 'ticket', title => 'A ticket waiting for its Jira ref',
);

ok( Tira::CLI::Records->can('import_jira'),
    'the record layer can import a Jira XML export' );

my $xml = File::Spec->catfile( $tmp, 'sample.xml' );
open my $fh, '>', $xml or die $!;
print {$fh} <<'XML';
<rss version="0.92"><channel><item>
  <title>[PROJ-123] Summary text</title>
  <key id="12345">PROJ-123</key>
  <summary>Summary &amp; more &lt;text&gt;</summary>
  <status>Open</status>
  <description><![CDATA[Contains a literal </item> string that must not end the match early.]]></description>
  <parent>PROJ-100</parent>
  <subtasks><subtask id="1">PROJ-124</subtask><subtask id="2">PROJ-125</subtask></subtasks>
</item></channel></rss>
XML
close $fh;

my $result = Tira::CLI::Records::import_jira(
    $tira, { project => $root, ref => $target->{ref}, author => 'alice', files => [$xml] }, {},
);
ok( $result->{ok}, 'importing a well-formed export succeeds' );
is( $result->{jira_key}, 'PROJ-123', 'the parsed Jira key comes back in the result' );

my $after = $tira->record_show( project => $root, type => 'ticket', ref => $target->{ref} );
my $key_details_text = join( "\n", @{ $after->{key_details} // [] } );
like( $key_details_text, qr/PROJ-123/,
    'the Jira key is recorded as a key-detail on the Tira ticket' );
like( $key_details_text, qr/Summary & more <text>/,
    'XML entities are decoded rather than stored literally' );
unlike( $key_details_text, qr/CDATA|<\/item>/,
    'the CDATA-wrapped description text (with its embedded literal </item>) never reaches the key-detail - only key+summary are stored' );

# --- a genuine export, exactly as the owner attached it --------------------
#
# Michael attached a real "Export XML" download to this ticket (2026-09-24)
# and asked for the implementation to be re-evaluated against it, rather
# than only the hand-built fixtures above. Kept verbatim, including the
# leading "This XML file does not appear to have any style information..."
# line a browser's own XML viewer prepends when the page is saved directly -
# proof the parser does not assume the file starts with the XML declaration.
# The <description> field alone carries several KB of unescaped inline HTML
# (<h3>, <p>, <ul>, <li>, <a href=...>) and a literal apostrophe-heavy prose
# comment - none of it reaches the key-detail, since only <key>/<summary>
# are ever parsed, but it is real content this regex-based extractor must
# not trip over while finding them.

my $real = File::Spec->catfile( $tmp, 'real-export.xml' );
open my $rfh, '>', $real or die $!;
print {$rfh} <<'REALJIRA';
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<!--
RSS generated by JIRA (1001.0.0-SNAPSHOT#100294-rev:ec37f3f0c9440c45ed80010e91f81d16c61a2796) at Thu Sep 24 00:25:09 UTC 2026

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
 -->
<rss version="0.92">
<channel>
<title>Jira</title>
<link>https://richmanbrown986.atlassian.net</link>
<description>This file is an XML representation of an issue</description>
<language>en-gb</language>
<build-info>
<version>1001.0.0-SNAPSHOT</version>
<build-number>100294</build-number>
<build-date>23-09-2026</build-date>
</build-info>
<item>
<title>[ZSD-3] Choose the simulation design direction (10 options delivered)</title>
<link>https://richmanbrown986.atlassian.net/browse/ZSD-3</link>
<project id="10001" key="ZSD">Zenandi Software Development</project>
<description><h3><a name="Problem"></a>Problem</h3> <p>Concept Note V7.4 names the simulation as the centrepiece of the product: "Both routes use simulation. Play a Month. Play a Term." It splits Action explicitly into two halves - the simulations AND the questions.</p> <ul> <li>Play a Month - the canonical V7.4 design; a month of the learner's life, week by week.</li> <li>The Feeling Meter - money mood as the interface; the learner watches their own pattern draw itself.</li> </ul> <h3><a name="Scope"></a>Scope</h3> <ul> <li>IN: the owner's pick of one design direction, plus the reward question and the session-length question, which cannot be answered separately from it.</li> </ul> </description>
<environment/>
<key id="10010">ZSD-3</key>
<summary>Choose the simulation design direction (10 options delivered)</summary>
<type id="10005" iconUrl="https://richmanbrown986.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10300?size=medium">Story</type>
<priority id="4" iconUrl="https://richmanbrown986.atlassian.net/images/icons/priorities/low_new.svg">Low</priority>
<status id="10007" iconUrl="https://richmanbrown986.atlassian.net/images/icons/statuses/generic.png" description="">Backlog</status>
<statusCategory id="2" key="new" colorName="blue-gray"/>
<resolution id="-1">Unresolved</resolution>
<assignee accountid="712020:97ef9e6b-5938-482b-a943-317341339a3b">Michael Vu</assignee>
<reporter accountid="712020:97ef9e6b-5938-482b-a943-317341339a3b">Michael Vu</reporter>
<labels>
<label>Zenandi-Developer</label>
</labels>
<created>Fri, 31 Jul 2026 01:36:39 +0100</created>
<updated>Fri, 31 Jul 2026 13:07:45 +0100</updated>
<due/>
<votes>0</votes>
<watches>1</watches>
<comments>
<comment id="10004" author="712020:97ef9e6b-5938-482b-a943-317341339a3b" created="Fri, 31 Jul 2026 11:54:12 +0100"><p>Michael - this card was rewritten to the ticket standard today, but the decision itself was deliberately not guessed.</p></comment>
</comments>
<attachments>
<attachment id="10005" name="zenandi-simulation-options-v1.0.pdf" size="526202" author="ea9c6fa0-d4ff-4bed-a609-18b0fc7d999b" created="Fri, 31 Jul 2026 10:38:11 +0100"/>
</attachments>
<subtasks> </subtasks>
<customfields>
<customfield id="customfield_10042" key="com.atlassian.jira.plugin.system.customfieldtypes:select">
<customfieldname>SDLC Gate</customfieldname>
<customfieldvalues>
<customfieldvalue key="10022">
<![CDATA[ G2 ]]>
</customfieldvalue>
</customfieldvalues>
</customfield>
</customfields>
</item>
</channel>
</rss>
REALJIRA
close $rfh;

my $real_target = $tira->create_record(
    project => $root, type => 'ticket', title => 'A ticket waiting for its real Jira ref',
);
my $real_result = Tira::CLI::Records::import_jira(
    $tira, { project => $root, ref => $real_target->{ref}, author => 'alice', files => [$real] }, {},
);
ok( $real_result->{ok}, 'importing the owner\'s own real export succeeds' );
is( $real_result->{jira_key}, 'ZSD-3', 'the real export\'s key is parsed correctly' );
is( $real_result->{summary}, 'Choose the simulation design direction (10 options delivered)',
    'and its summary is parsed correctly, despite several KB of unescaped inline HTML in <description> between <key> and <summary>' );

my $real_after = $tira->record_show( project => $root, type => 'ticket', ref => $real_target->{ref} );
my $real_key_details_text = join( "\n", @{ $real_after->{key_details} // [] } );
like( $real_key_details_text, qr/ZSD-3/, 'the real key reaches the key-detail' );
unlike( $real_key_details_text, qr/<h3>|<ul>|<li>/, 'none of the embedded description HTML leaks into the key-detail' );

# --- a CDATA-wrapped summary is unwrapped too, not only entity-decoded ----

is( Tira::CLI::Records::_xml_unescape('<![CDATA[Wrapped & unescaped]]>'), 'Wrapped & unescaped',
    'a CDATA-wrapped value returns its inner text verbatim, not re-decoded as entities' );

# --- a malformed file refuses (dies), not a silent {ok=>0} success --------

my $bad = File::Spec->catfile( $tmp, 'bad.xml' );
open my $bfh, '>', $bad or die $!;
print {$bfh} "not xml at all, just text\n";
close $bfh;

my $before_ticket = $tira->record_show( project => $root, type => 'ticket', ref => $target->{ref} );
eval {
    Tira::CLI::Records::import_jira(
        $tira, { project => $root, ref => $target->{ref}, author => 'alice', files => [$bad] }, {},
    );
};
like( $@, qr/no <key> tag found/, 'a malformed file dies naming what was expected, not a silent ok=>0' );

my $after_bad = $tira->record_show( project => $root, type => 'ticket', ref => $target->{ref} );
is_deeply( $after_bad->{key_details}, $before_ticket->{key_details},
    'the ticket is unchanged after a refused import' );

# --- a multi-issue export refuses by name, rather than silently picking ---
# --- the first issue and importing the wrong one ---------------------------

my $multi = File::Spec->catfile( $tmp, 'multi.xml' );
open my $mfh, '>', $multi or die $!;
print {$mfh} <<'XML';
<rss version="0.92"><channel>
<item><key id="1">PROJ-201</key><summary>First</summary></item>
<item><key id="2">PROJ-202</key><summary>Second</summary></item>
</channel></rss>
XML
close $mfh;

eval {
    Tira::CLI::Records::import_jira(
        $tira, { project => $root, ref => $target->{ref}, author => 'alice', files => [$multi] }, {},
    );
};
like( $@, qr/PROJ-201.*PROJ-202|exactly one issue/s,
    'an export naming more than one issue refuses by name rather than silently importing the first' );

# --- no silent 'claude' author default - an unknown/unset author refuses --
# --- through the same path every other command already uses --------------

eval {
    Tira::CLI::Records::import_jira(
        $tira, { project => $root, ref => $target->{ref}, files => [$xml] }, {},
    );
};
ok( $@, 'with no --author supplied, the call refuses rather than silently attributing the import to a guessed person' );

# --- the real installed executable, not only the engine sub ---------------

my $exe = File::Spec->catfile( qw(skills import cli jira) );
ok( -x $exe, 'the real tira.import.jira executable exists and is runnable' );

my $out  = `$^X -I lib $exe --ref @{[$target->{ref}]} --file $bad --project $root --author alice 2>&1`;
my $exit = $? >> 8;
isnt( $exit, 0, 'running the real executable against a malformed file exits non-zero' );

done_testing();

__END__

=head1 NAME

1160-a-key-that-crossed-boards.t - importing a Jira issue XML export onto a Tira ticket

=head1 DESCRIPTION

TKT-1153. C<Tira::CLI::Records::import_jira> parses a Jira issue-XML export
(the standard "Export XML" action's RSS 0.92 shape) and records the Jira
issue key and summary as a key-detail on the target Tira ticket, via the
existing C<comment_add --key-detail> mechanism. XML entities and CDATA are
decoded rather than stored literally; an export naming more than one issue,
a file with no recognizable C<E<lt>keyE<gt>> tag, or a call with no author
all refuse (die) cleanly rather than succeeding silently or crashing with an
internal parser error.

=cut
