#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
BEGIN {
    my $lib = "$FindBin::Bin/../../../lib";
    $lib =~ /\A([^\x00-\x1f\x7f]+)\z/ or die "Unsafe Tira library path\n";
    unshift @INC, $1;
}
use Tira::CLI;
exit Tira::CLI->run( command => 'record.create', type => 'epic', argv => \@ARGV );

__END__

=head1 NAME

tira.epic.create - Create a free-ranging epic in Backlog

=cut
